-- Drop statements 
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TYPE IF EXISTS public.account_type CASCADE;

-- Create enum for Client, Employee, Admin
CREATE TYPE public.account_type AS ENUM(
'Client',
'Employee',
'Admin');

-- Create relationship between `classification` and `inventory` tables
CREATE TABLE public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY, 
  classification_name CHARACTER VARYING NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table `account`
CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Table structure for table `inventory`
CREATE TABLE public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between `classification` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- Data for table `classification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'), 
('Sport'),
('SUV'),
('Truck'),
('Sedan');

INSERT INTO public.inventory (inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id)
VALUES (
'Chevy',
'Camaro',
'2018',
'Cool car!',
'/images/camaro.jpg',
'/images/camaro-tn.jpg',
25000,
101222,
'Silver', 
2
),(
'Batmobile',
'Custom',
'2007',
'Super hero car',
'/images/batmobile.jpg',
'/images/batmobile-tn.jpg',
65000,
29887,
'Black',
1
),(
'FBI',
'Surveillance Van',
'2016',
'Police shows',
'/images/survan.jpg',
'/images/survan-tn.jpg',
20000,
19851,
'Brown',
1
),(
'Dog ',
'Car',
'1997',
'Fluffy ears',
'/images/dog-car.jpg',
'/images/dog-car-tn.jpg',
35000,
71632,
'White', 
1
),(
'Jeep',
'Wrangler',
'2019',
'Offroading',
'/images/wrangler.jpg',
'/images/wrangler-tn.jpg',
28045, 
41205,
'Yellow',
3
),(
'Lamborghini', 
'Adventador',
'2016',
'V-12 punch',
'/images/adventador.jpg',
'/images/adventador-tn.jpg',
417650,
71003,
'Blue',
2
),(
'Aerocar',
'Aerocar',
'1963',
'Airplane car',
'/images/aerocar.jpg',
'/images/aerocar-tn.jpg',
700000,
18956,
'Red', 
1
),(
'Monster',
'Truck',
'1995', 
'60 inch tires',
'/images/monster-truck.jpg',
'/images/monster-truck-tn.jpg',
150000,
3998,
'purple',
1
),(
'Cadillac',
'Escalade',
'2019',
'Luxurious',
'/images/escalade.jpg',
'/images/escalade-tn.jpg',
75195, 
41958, 
'Black',
4
),(
'GM',
'Hummer',
'2016',
'The Hummer has small interiors...',
'/images/hummer.jpg',
'/images/hummer-tn.jpg',
58800,
56564,
'Yellow',
4
),(
'Mechanic',
'Special',
'1964',
'TLC needed',
'/images/mechanic.jpg',
'/images/mechanic-tn.jpg',
100,
200125,
'Rust',
5
),(
'Ford',
'Model T',
'1921',
'First production',
'/images/model-t.jpg',
'/images/model-t-tn.jpg',
30000,
26357,
'Black',
5
),(
'Mystery',
'Machine',
'1999',
'Scooby gang',
'/images/mystery-van.jpg',
'/images/mystery-van-tn.jpg',
10000,
128564,
'Green',
1
),(
'Spartan',
'Fire Truck',
'2012', 
'1000 gallon tank',
'/images/fire-truck.jpg',
'/images/fire-truck-tn.jpg',
50000, 
38522,
'Red',
4
),('Ford',
'Crown Victoria',
'2013', 'Police force', 
'/images/crwn-vic.jpg',
'/images/crwn-vic-tn.jpg',
10000,
108247, 
'White',
5
);

-- Hummer Update
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

-- Tony Stark Update
INSERT INTO public.account (account_firstname, account_lastname, account_email, account_password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

UPDATE public.account 
SET account_type = 'Admin' 
WHERE account_id = 1;

DELETE FROM public.account 
WHERE account_id = 1;
